version: 2
jobs:
  build:
    macos:
      xcode: "11.3.0"

    steps:
      - checkout

      - run:
          name: Install Solidity
          command: |
            brew update
            #brew tap ethereum/ethereum # Acutally we should use the rule from the pull request
            brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/${CIRCLE_SHA1}/solidity.rb

      - run:
          name: Test Formula
          command: brew test solidity

      - run:
          name: Test Solidity
          command: solc --version

      - run:
          name: Cleanup
          command: brew uninstall boost cmake ccache solidity

      - run:
          name: Install Solidity 0.5
          command: |
            brew update
            #brew tap ethereum/ethereum # Acutally we should use the rule from the pull request
            brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/${CIRCLE_SHA1}/solidity@5.rb

      - run:
          name: Test Formula
          command: brew test solidity@5

      - run:
          name: Test Solidity
          command: solc --version

      - run:
          name: Cleanup
          command: brew uninstall boost cmake ccache solidity@5

      - run:
          name: Install Solidity 0.4
          command: |
            brew update
            #brew tap ethereum/ethereum # Acutally we should use the rule from the pull request
            brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/${CIRCLE_SHA1}/solidity@4.rb

      - run:
          name: Test Formula
          command: brew test solidity@4

      - run:
          name: Test Solidity
          command: solc --version

      - run:
          name: Install geth
          command: brew install https://raw.githubusercontent.com/ethereum/homebrew-ethereum/${CIRCLE_SHA1}/ethereum.rb
